datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

start = textbook
    textbook = element textbook {book_title, section*, chapter*}
        book_title = element book_title {text}
        section = element section {mixed{chapter+}}
            chapter = element chapter {title, caption*, p*}
                caption = element caption {text}
                title = element title {n, text}
                    n = attribute n {xsd:int}
                p = element p {mixed{(person | people | place | political_affiliation | religion | territory | event | system | gov)*}}
                territory = element territory {territory_type, text}
                    territory_type = attribute territory_type {"kingdom" | "country" | "region" }
                place = element place {place_type, text}

                    place_type = attribute place_type {"building" | "street" | "city" | "river" | "mountain" | "water_body" | "plain"}
#                    figured water_body can represent anything like a lake/ocean/sea, but kept river separate cause it feels different enough. we can change if you guys want
                person = element person {person_type?, text} #made attribute optional for now bc of accounting for Pugachev, Lomonosov, etc
                    person_type= attribute person_type {"russian_royalty"|"tsar"|"foreign_leader"|"musician"|"knyaz"|"rebel"|"worker"|"politician"}

                people = element people {people_type, text}
                    people_type= attribute people_type {"ethnicity" | "class" | "job"}
                political_affiliation = element political_affiliation {political_type, text}
                    political_type = attribute political_type {text}
                religion = element religion {religion_type, text}
                    religion_type = attribute religion_type {"orthodox" | "muslim" | "jewish" | "pagan" | "athiest"}
                event = element event {event_type, text}
	               event_type = attribute event_type {"major" | "minor"}
	               
	           system = element system {system_type, text} #new
	               system_type = attribute system_type {"communism" | "socialism" | "capitalism" }
	           gov = element gov {gov_type, text}
	               gov_type = attribute gov_type {"executive" | "legislative" | "judiciary" }