datatypes xsd = "http://www.w3.org/2001/XMLSchema-datatypes"

start = textbook
textbook = element textbook {book_title, section*, chapter*}
    book_title = element book_title {text}
    section = element section {section_title, mixed{chapter+}}
        section_title = element section_title {s, text}
            s= attribute s {xsd:int}
    chapter = element chapter {title, p*}
        title = element title {n, text}
            n = attribute n {xsd:int}
        p = element p {mixed{(person | people | place | political_affiliation | religion | territory | event | system | gov | rhetoric |organization | date)*}}
            id = attribute id { text }
            territory = element territory {id?, territory_type, text}
                territory_type = attribute territory_type {"kingdom" | "country" | "region" }
            place = element place {id?, place_type, text}
                place_type = attribute place_type {"building" | "street" | "city" | "river" | "mountain" | "water_body" | "plain"}
    #                    figured water_body can represent anything like a lake/ocean/sea, but kept river separate cause it feels different enough. we can change if you guys want
            person = element person {id?, person_type?, text}
                person_type= attribute person_type {"russian_royalty"|"tsar"|"foreign_leader"|"artist"|"knyaz"|"rebel"|"worker"|"politician"|"military"}
            people = element people {id?, people_type, text}
                people_type= attribute people_type {"ethnicity" | "class" | "job" | "army"}
            political_affiliation = element political_affiliation {political_type, text}
                political_type = attribute political_type {text}
            religion = element religion {id?, religion_type, text}
                religion_type = attribute religion_type {"orthodox" | "muslim" | "jewish" | "pagan" | "athiest"}
            event = element event {id?, event_type, text}
                event_type = attribute event_type {"major" | "minor"}
            system = element system {id?, system_type, text} #new
                system_type = attribute system_type {"communism" | "socialism" | "capitalism" | "serfdom" }
            gov = element gov {id?, gov_type, text}
                gov_type = attribute gov_type {"executive" | "legislative" | "judiciary" }
            organization = element organization {id?, organization_type, text}
                organization_type = attribute organization_type {"agriculture"}
            
            #rhetoric marks up strong language for the propaganda timeline/chart; attribute types are from the US IPA's list (linked on website)
            rhetoric = element rhetoric {type,text}
	               type= attribute type {"nc" |"generality" |"transfer" |"testimonial" |"pf" |"stacking" |"bw"}
	               
	        #date element used for the event timeline
	        #includes id? so that elements inside <date> may still have the @id attribute and a popup
            date = element date {id?, date_type, mixed{(year | month | day)*}, mixed{ a | b | c | d | e | f | g | h | i | j | k}*, text}
                date_type = attribute date_type {"major" | "minor"}
                year = attribute year {xsd:int}
                month = attribute month {xsd:int | text}
                day = attribute day {xsd:int} 
                a = element territory {id?, a_type, text}
                    a_type = attribute territory_type {"kingdom" | "country" | "region" }
                b= element place {id?, b_type, text}
                    b_type = attribute place_type {"building" | "street" | "city" | "river" | "mountain" | "water_body" | "plain"}
                c = element person {id?, c_type?, text}
                    c_type= attribute person_type {"russian_royalty"|"tsar"|"foreign_leader"|"artist"|"knyaz"|"rebel"|"worker"|"politician"|"military"}
                d = element people {id?, d_type, text}
                    d_type= attribute people_type {"ethnicity" | "class" | "job" | "army"}
                e = element political_affiliation {id?, e_type, text}
                    e_type = attribute political_type {text}
                f = element religion {id?, f_type, text}
                    f_type = attribute religion_type {"orthodox" | "muslim" | "jewish" | "pagan" | "athiest"}
                g = element event {id?, g_type, text}
                    g_type = attribute event_type {"major" | "minor"}
                h = element system {id?, h_type, text}
                    h_type = attribute system_type {"communism" | "socialism" | "capitalism" | "serfdom" }
                i = element gov {id?, i_type, text}
                    i_type = attribute gov_type {"executive" | "legislative" | "judiciary" }
                j = element organization {id?, j_type, text}
                    j_type = attribute organization_type {"agriculture"}
                k = element rhetoric {id?, k_type, text}
                    k_type = attribute about {text}